use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum OpCode {
    LoadConst(usize),
    LoadLocal(usize),
    StoreLocal(usize),
    LoadGlobal(String),
    StoreGlobal(String),
    Pop,
    Add,
    Sub,
    Mul,
    Div,
    Mod,
    IntDiv,
    Neg,
    Eq,
    Ne,
    Lt,
    Le,
    Gt,
    Ge,
    And,
    Or,
    Not,
    Concat,
    Jump(usize),
    JumpIfFalse(usize),
    JumpIfTrue(usize),
    Call(usize),
    CallTool(usize),
    Return,
    MakeList(usize),
    MakeMap(usize),
    GetField(String),
    MakeSome,
    MakeOk,
    MakeErr,
    Unwrap,
    IsOk,
    IsSome,
    Print,
    Halt,
}
