use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum OpCode {
    LoadConst(usize),
    LoadLocal(usize),
    StoreLocal(usize),
    LoadGlobal(String),
    StoreGlobal(String),
    Pop,
    Add,
    Sub,
    Mul,
    Div,
    Mod,
    IntDiv,
    Neg,
    Eq,
    Ne,
    Lt,
    Le,
    Gt,
    Ge,
    And,
    Or,
    Not,
    Concat,
    Jump(usize),
    JumpIfFalse(usize),
    JumpIfTrue(usize),
    Call(usize),
    CallTool(usize),
    /// Call a stdlib builtin by name with N args already on the stack.
    CallBuiltin(String, usize),
    /// Call a method on an object: stack has [args..., target]. Pop target + args, dispatch.
    CallMethod(String, usize),
    Return,
    MakeList(usize),
    MakeMap(usize),
    GetField(String),
    MakeSome,
    MakeOk,
    MakeErr,
    Unwrap,
    IsOk,
    IsSome,
    /// Duplicate the top-of-stack value.
    Dup,
    /// Peek TOS (must be Variant); push Bool: does it have this name?
    IsVariant(String),
    /// Pop TOS (must be Variant); push payload[index].
    ExtractPayload(usize),
    Print,
    Halt,
}
